package com.proyecto.principal;
// Generated 8/10/2014 10:08:39 PM by Hibernate Tools 4.3.1



/**
 * ArticuloSucursal generated by hbm2java
 */
public class ArticuloSucursal  implements java.io.Serializable {


     private ArticuloSucursalId id;
     private Articulo articulo;
     private Sucursal sucursal;
     private int unidad;

    public ArticuloSucursal() {
    }

    public ArticuloSucursal(ArticuloSucursalId id, Articulo articulo, Sucursal sucursal, int unidad) {
       this.id = id;
       this.articulo = articulo;
       this.sucursal = sucursal;
       this.unidad = unidad;
    }
   
    public ArticuloSucursalId getId() {
        return this.id;
    }
    
    public void setId(ArticuloSucursalId id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public int getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(int unidad) {
        this.unidad = unidad;
    }




}


