package com.proyecto.principal;
// Generated 8/10/2014 10:08:39 PM by Hibernate Tools 4.3.1



/**
 * ArticuloSucursalId generated by hbm2java
 */
public class ArticuloSucursalId  implements java.io.Serializable {


     private int articuloIdArticulo;
     private int sucursalIdSucursal;

    public ArticuloSucursalId() {
    }

    public ArticuloSucursalId(int articuloIdArticulo, int sucursalIdSucursal) {
       this.articuloIdArticulo = articuloIdArticulo;
       this.sucursalIdSucursal = sucursalIdSucursal;
    }
   
    public int getArticuloIdArticulo() {
        return this.articuloIdArticulo;
    }
    
    public void setArticuloIdArticulo(int articuloIdArticulo) {
        this.articuloIdArticulo = articuloIdArticulo;
    }
    public int getSucursalIdSucursal() {
        return this.sucursalIdSucursal;
    }
    
    public void setSucursalIdSucursal(int sucursalIdSucursal) {
        this.sucursalIdSucursal = sucursalIdSucursal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticuloSucursalId) ) return false;
		 ArticuloSucursalId castOther = ( ArticuloSucursalId ) other; 
         
		 return (this.getArticuloIdArticulo()==castOther.getArticuloIdArticulo())
 && (this.getSucursalIdSucursal()==castOther.getSucursalIdSucursal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getArticuloIdArticulo();
         result = 37 * result + this.getSucursalIdSucursal();
         return result;
   }   


}


