package com.proyecto.principal;
// Generated 18/11/2014 09:37:45 PM by Hibernate Tools 4.3.1



/**
 * Comentarios generated by hbm2java
 */
public class Comentarios  implements java.io.Serializable {


     private Integer idComentarios;
     private Articulo articulo;
     private String comentario;
     private String autor;

    public Comentarios() {
    }

    public Comentarios(Articulo articulo, String comentario, String autor) {
       this.articulo = articulo;
       this.comentario = comentario;
       this.autor = autor;
    }
   
    public Integer getIdComentarios() {
        return this.idComentarios;
    }
    
    public void setIdComentarios(Integer idComentarios) {
        this.idComentarios = idComentarios;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }




}


