package com.proyecto.principal;
// Generated 8/10/2014 10:08:39 PM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String nombreEmpresa;
     private String fondoColor;
     private String fondoImagen;

    public Empresa() {
    }

	
    public Empresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public Empresa(String nombreEmpresa, String fondoColor, String fondoImagen) {
       this.nombreEmpresa = nombreEmpresa;
       this.fondoColor = fondoColor;
       this.fondoImagen = fondoImagen;
    }
   
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getFondoColor() {
        return this.fondoColor;
    }
    
    public void setFondoColor(String fondoColor) {
        this.fondoColor = fondoColor;
    }
    public String getFondoImagen() {
        return this.fondoImagen;
    }
    
    public void setFondoImagen(String fondoImagen) {
        this.fondoImagen = fondoImagen;
    }




}


