package com.proyecto.principal;
// Generated 17/11/2014 10:10:26 PM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String nombreEmpresa;
     private String fondoColor;
     private String fondoImagen;
     private String orientacion;

    public Empresa() {
    }

	
    public Empresa(String nombreEmpresa, String orientacion) {
        this.nombreEmpresa = nombreEmpresa;
        this.orientacion = orientacion;
    }
    public Empresa(String nombreEmpresa, String fondoColor, String fondoImagen, String orientacion) {
       this.nombreEmpresa = nombreEmpresa;
       this.fondoColor = fondoColor;
       this.fondoImagen = fondoImagen;
       this.orientacion = orientacion;
    }
   
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getFondoColor() {
        return this.fondoColor;
    }
    
    public void setFondoColor(String fondoColor) {
        this.fondoColor = fondoColor;
    }
    public String getFondoImagen() {
        return this.fondoImagen;
    }
    
    public void setFondoImagen(String fondoImagen) {
        this.fondoImagen = fondoImagen;
    }
    public String getOrientacion() {
        return this.orientacion;
    }
    
    public void setOrientacion(String orientacion) {
        this.orientacion = orientacion;
    }




}


