package com.proyecto.principal;
// Generated 6/11/2014 09:41:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer idSucursal;
     private String nombreSucursal;
     private String direccion;
     private int numeroTelefonico;
     private String email;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Articulosucursal> articulosucursals = new HashSet<Articulosucursal>(0);

    public Sucursal() {
    }

	
    public Sucursal(String nombreSucursal, String direccion, int numeroTelefonico, String email) {
        this.nombreSucursal = nombreSucursal;
        this.direccion = direccion;
        this.numeroTelefonico = numeroTelefonico;
        this.email = email;
    }
    public Sucursal(String nombreSucursal, String direccion, int numeroTelefonico, String email, Set<Usuario> usuarios, Set<Articulosucursal> articulosucursals) {
       this.nombreSucursal = nombreSucursal;
       this.direccion = direccion;
       this.numeroTelefonico = numeroTelefonico;
       this.email = email;
       this.usuarios = usuarios;
       this.articulosucursals = articulosucursals;
    }
   
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getNumeroTelefonico() {
        return this.numeroTelefonico;
    }
    
    public void setNumeroTelefonico(int numeroTelefonico) {
        this.numeroTelefonico = numeroTelefonico;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Articulosucursal> getArticulosucursals() {
        return this.articulosucursals;
    }
    
    public void setArticulosucursals(Set<Articulosucursal> articulosucursals) {
        this.articulosucursals = articulosucursals;
    }




}


