package com.proyecto.principal;
// Generated 9/10/2014 09:43:16 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Sucursal sucursal;
     private String nombreUsuario;
     private String password;
     private char permiso;

    public Usuario() {
    }

    public Usuario(Sucursal sucursal, String nombreUsuario, String password, char permiso) {
       this.sucursal = sucursal;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.permiso = permiso;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(char permiso) {
        this.permiso = permiso;
    }




}


